### ISSUE TITLE
Certifications image are not getting load

### ISSUE THREAD

**Issue by iatharva** [iatharva/iatharva.github.io#5]

**Comment by iatharva** [comment]
Checked the path for the images which looks like the correct ones.

**Comment by iatharva** [comment]
Images are loaded and working while tested on local.

**Comment by chwonseok** [comment]
Hey, I've had this issue before, and I tried to add `./` right before image address

so it'd be like

```html
...
<section id="photos">
        <img src="./images/Certificates/1comptia.PNG">
        <img src="./images/Certificates/2UI.PNG">
...
```

It is about Absolute Path, and Relative Path, in case that you wanna search for.
I hope it works!

**Comment by iatharva** [comment]
Thanks @chwonseok I will try that

**Comment by iatharva** [comment]
I tried making the changes which you suggested @chwonseok but not working, 
(A temporary solution would be to replace the path with a link to the hosted image from my repository)

**Comment by chwonseok** [comment]
@iatharva Sorry to hear that it didn't work I hope you will find better solution soon!

**Comment by iatharva** [comment]
The issue was occurring due to extension i.e. `.PNG` written in uppercase, writing it in lower case solved the issue.
